# Generated by Django 2.1.7 on 2019-04-09 13:24

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HallInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='宴会厅名称')),
                ('area', models.IntegerField(help_text='整数', verbose_name='面积')),
                ('height', models.FloatField(help_text='浮点数', verbose_name='层高')),
                ('maxPeople', models.IntegerField(help_text='整数', verbose_name='歌剧式人数')),
                ('kezhuoMaxPeople', models.IntegerField(help_text='整数', verbose_name='课桌式人数')),
                ('yuanzhuoMaxTable', models.IntegerField(help_text='整数', verbose_name='圆桌式桌数')),
                ('allDayPrice', models.IntegerField(help_text='整数', verbose_name='全天价格')),
                ('halfDayPrice', models.IntegerField(help_text='整数', verbose_name='半天价格')),
            ],
            options={
                'verbose_name': '宴会厅管理',
                'verbose_name_plural': '宴会厅管理',
            },
        ),
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='酒店名称')),
                ('city', models.CharField(default='上海市', help_text='默认：上海市', max_length=30, verbose_name='城市')),
                ('area', models.CharField(help_text='举例： 浦东新区', max_length=20, verbose_name='行政区域')),
                ('address', models.CharField(max_length=40, verbose_name='地址')),
                ('guestRoomReferencePrice', models.IntegerField(verbose_name='平均房价')),
                ('minMealCost', models.IntegerField(help_text='整数', verbose_name='最低餐标')),
                ('introDoc', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='PDF')),
                ('image', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Image')),
                ('description', models.TextField(verbose_name='场地简介')),
            ],
            options={
                'verbose_name': '场地管理',
                'verbose_name_plural': '场地管理',
            },
        ),
    ]
