# Generated by Django 2.1.7 on 2019-04-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeinfo',
            name='ballrooms',
            field=models.ManyToManyField(related_name='ballrooms', to='backend.HallInfo'),
        ),
    ]
