# Generated by Django 2.1.7 on 2019-04-09 14:32

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_placeinfo_ballrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='图片标示')),
                ('image', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Image')),
            ],
            options={
                'verbose_name': '场地图片管理',
                'verbose_name_plural': '场地图片管理',
            },
        ),
    ]
