# Generated by Django 2.1.7 on 2019-04-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_imageinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='placeinfo',
            name='image',
            field=models.ManyToManyField(related_name='images', to='backend.ImageInfo'),
        ),
    ]
