# Generated by Django 2.1.7 on 2019-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190409_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40, verbose_name='标示')),
                ('type', models.CharField(max_length=15, verbose_name='房型')),
                ('bedType', models.CharField(max_length=10, verbose_name='床型')),
                ('area', models.IntegerField(help_text='整数', verbose_name='面积')),
                ('amount', models.IntegerField(help_text='整数', verbose_name='数量')),
                ('network', models.CharField(default='有', max_length=5, verbose_name='宽带')),
                ('price', models.IntegerField(help_text='整数', verbose_name='刊例价')),
            ],
            options={
                'verbose_name': '客房信息',
                'verbose_name_plural': '客房信息',
            },
        ),
        migrations.AddField(
            model_name='hallinfo',
            name='tag',
            field=models.CharField(default='a', max_length=40, unique=True, verbose_name='标示'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeinfo',
            name='guestRoomReferencePrice',
            field=models.IntegerField(help_text='整数', verbose_name='平均房价'),
        ),
        migrations.AddField(
            model_name='placeinfo',
            name='rooms',
            field=models.ManyToManyField(related_name='rooms', to='backend.GuestRoom'),
        ),
    ]
