# Generated by Django 2.1.7 on 2019-04-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190409_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinfo',
            name='image',
            field=models.ManyToManyField(help_text='用于展示酒店图片', related_name='images', to='backend.ImageInfo'),
        ),
    ]
