# Generated by Django 2.1.7 on 2019-04-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190414_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinfo',
            name='ballrooms',
            field=models.ManyToManyField(related_name='ballrooms', to='backend.HallInfo', verbose_name='宴会厅'),
        ),
    ]
