# Generated by Django 2.1.7 on 2019-04-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190416_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestroom',
            name='network',
        ),
        migrations.AlterField(
            model_name='hallinfo',
            name='maxPeople',
            field=models.IntegerField(help_text='整数', verbose_name='剧院式人数'),
        ),
    ]
