# Generated by Django 2.1.7 on 2019-04-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190418_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallinfo',
            name='name',
            field=models.CharField(max_length=40, verbose_name='宴会厅名称'),
        ),
    ]
